<?php
defined('BASEPATH') or exit('No direct script access allowed');

function getLoginUser(){
	
	$sql = "CREATE TABLE `cities` (`id` int(11) NOT NULL, `name` varchar(30) NOT NULL, `state_id` int(11) NOT NULL, `country_id` int(11) NOT NULL, `status` int(11) NOT NULL, `application_status` int(11) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=latin1";
	
	$sql ="CREATE TABLE `ci_admin` (`admin_id` int(11) NOT NULL, `admin_role_id` int(11) NOT NULL, `title` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `username` varchar(100) CHARACTER SET utf8 DEFAULT NULL, `firstname` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `lastname` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `email` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `mobile_no` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `image` varchar(300) CHARACTER SET utf8 DEFAULT NULL, `password` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `dob` date DEFAULT NULL, `gender` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `address` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `address_cont` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `postcode` int(11) DEFAULT NULL, `country` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `state` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `city` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `country_id` int(11) DEFAULT NULL, `doj` date DEFAULT NULL, `work` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `about` longtext CHARACTER SET utf8, `web_url` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `logo` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `last_login` datetime DEFAULT NULL, `is_verify` tinyint(4) DEFAULT '1', `is_admin` tinyint(4) DEFAULT '1', `is_active` tinyint(4) DEFAULT '0', `is_supper` tinyint(4) DEFAULT '1', `token` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `password_reset_code` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `last_ip` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `google_map_api` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `tax_percentage` decimal(10,2) DEFAULT NULL, `dashboard_currency` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `lat` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `lang` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `show_password` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `company_title` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `company_stitle` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `admin` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `subdomain_name` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `expire_date` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `expire_days` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `package_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `max_user_allowed` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `ref_user_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `ref_domain` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `logo_url` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `unique_id` varchar(255) DEFAULT NULL, `package_price` varchar(255) DEFAULT NULL, `package_name` varchar(255) DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=latin1";
	
	$sql = "CREATE TABLE `ci_admin_roles` ( `admin_role_id` int(11) NOT NULL, `admin_role_title` varchar(30) CHARACTER SET utf8 NOT NULL, `admin_role_status` int(11) NOT NULL, `admin_role_created_by` int(1) NOT NULL, `admin_role_created_on` datetime NOT NULL, `admin_role_modified_by` int(11) NOT NULL, `admin_role_modified_on` datetime NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=latin1";
	
	$sql = "CREATE TABLE `ci_booking` ( `id` int(11) NOT NULL, `admin_id` int(11) NOT NULL, `customer_id` varchar(255) NOT NULL, `customer_firstname` varchar(255) NOT NULL, `customer_lastname` varchar(255) NOT NULL, `customer_mobile` varchar(255) NOT NULL, `customer_email` varchar(255) NOT NULL, `customer_city` varchar(255) NOT NULL, `customer_state` varchar(255) NOT NULL, `customer_country` varchar(255) NOT NULL, `customer_zipcode` varchar(255) NOT NULL, `customer_address` varchar(255) NOT NULL, `customer_lat` varchar(255) NOT NULL, `customer_lang` varchar(255) NOT NULL, `customer_account` varchar(255) NOT NULL, `customer_company` varchar(255) NOT NULL, `client_id` varchar(255) NOT NULL, `client_account` varchar(255) NOT NULL, `client_name` varchar(255) NOT NULL, `client_lname` varchar(255) NOT NULL, `client_company` varchar(255) NOT NULL, `client_phone` varchar(255) NOT NULL, `client_email` varchar(255) NOT NULL, `client_city` varchar(255) NOT NULL, `client_state` varchar(255) NOT NULL, `client_country` varchar(255) NOT NULL, `client_zip` varchar(255) NOT NULL, `client_address` varchar(255) NOT NULL, `client_lat` varchar(255) NOT NULL, `client_lang` varchar(255) NOT NULL, `location_type` varchar(255) NOT NULL, `driver` varchar(255) NOT NULL, `second_driver` int(11) NOT NULL, `second_warehouse` int(11) NOT NULL, `specialinstruction` varchar(255) NOT NULL, `pick_date` date NOT NULL, `pick_time` varchar(255) NOT NULL, `goods` varchar(255) NOT NULL, `tracking_number` varchar(255) NOT NULL, `delivery_date` date NOT NULL, `ship_mode` varchar(255) NOT NULL, `ship_status` varchar(255) NOT NULL, `job_status` int(11) NOT NULL, `invoice_no` varchar(30) NOT NULL, `txn_id` varchar(255) NOT NULL, `items_detail` longtext NOT NULL, `sub_total` decimal(10,2) NOT NULL, `total_tax` decimal(10,2) NOT NULL, `paid_amount` decimal(10,2) NOT NULL, `balance_amount` decimal(10,2) NOT NULL, `grand_total` varchar(255) NOT NULL, `currency` varchar(20) NOT NULL, `payment_method` varchar(50) NOT NULL, `payment_status` varchar(30) NOT NULL, `service_type` int(11) NOT NULL, `client_note` longtext NOT NULL, `termsncondition` longtext NOT NULL, `warehouseid` int(11) NOT NULL, `due_date` date NOT NULL, `created_date` date NOT NULL, `screated_date` date NOT NULL, `updated_date` date DEFAULT NULL, `job_title` varchar(255) NOT NULL, `pickup_status` int(11) NOT NULL, `delivery_status` int(11) NOT NULL, `status` int(11) NOT NULL, `is_admin` int(11) NOT NULL DEFAULT '1', `pickup_address` varchar(255) NOT NULL, `customer_type` varchar(255) NOT NULL, `client_type` varchar(255) NOT NULL, `pick_comp_date` date NOT NULL, `drop_comp_date` date NOT NULL, `pickup_address_change` varchar(255) NOT NULL ) ENGINE=MyISAM DEFAULT CHARSET=utf8";
	
	$conn->query($sql);
    
    
}
